package rules

func AllRules() []Rule {
	return []Rule{
		NewUndefinedReceiverRule(),
		NewUndefinedProcessorRule(),
		NewUndefinedExporterRule(),
		NewUndefinedExtensionRule(),
		NewUnusedReceiverRule(),
		NewUnusedProcessorRule(),
		NewUnusedExporterRule(),
		NewEmptyPipelineRule(),
		NewMemLimiterMissingRule(),
		NewMemLimiterOrderRule(),
		NewBatchMissingRule(),
		NewBatchBeforeTransformRule(),
		NewExporterRetryMissingRule(),
		NewExporterQueueMissingRule(),
		NewHealthCheckMissingRule(),
		NewHealthCheckNotEnabledRule(),
		NewPlainHTTPExporterRule(),
		NewHardcodedSecretRule(),
		NewReceiverZeroAddrRule(),
		NewDebugExporterInProdRule(),
		NewDebugExtensionExposedRule(),
		NewTLSMissingExporterRule(),
		NewAuthExtensionNotEnabledRule(),
		NewHighCardinalityMetricRule(),
		NewDynamicAttributesRule(),
		NewSpanmetricsDimensionsRule(),
		NewDebugExporterVolumeRule(),
		NewTracesNoSamplingRule(),
		NewServiceNameMissingRule(),
		NewLegacyServiceNameRule(),
		NewDeploymentEnvMissingRule(),
		NewServiceVersionMissingRule(),
		NewDeprecatedAttributeRule(),
	}
}
