package rules

type RuleDoc struct {
	Title           string
	Category        string
	DefaultSeverity string
	Why             string
	BadExample      string
	GoodExample     string
	HowToFix        string
}

var ruleDocs = map[string]RuleDoc{
	"OTEL-STRUCT-001": {
		Title: "Undefined receiver reference",
		Category: "structural",
		DefaultSeverity: "critical",
		Why: "A pipeline references a receiver that is not defined in the receivers section. The collector will fail to start.",
		BadExample: "service:\n  pipelines:\n    traces:\n      receivers: [missing_rcv]",
		GoodExample: "receivers:\n  otlp:\n    protocols:\n      grpc: {}\nservice:\n  pipelines:\n    traces:\n      receivers: [otlp]",
		HowToFix: "Define the missing receiver in the receivers section, or remove the reference from the pipeline.",
	},
	"OTEL-STRUCT-002": {
		Title: "Undefined processor reference",
		Category: "structural",
		DefaultSeverity: "critical",
		Why: "A pipeline references a processor that is not defined in the processors section. The collector will fail to start.",
		BadExample: "service:\n  pipelines:\n    traces:\n      processors: [missing_proc]",
		GoodExample: "processors:\n  batch: {}\nservice:\n  pipelines:\n    traces:\n      processors: [batch]",
		HowToFix: "Define the missing processor in the processors section, or remove the reference from the pipeline.",
	},
	"OTEL-STRUCT-003": {
		Title: "Undefined exporter reference",
		Category: "structural",
		DefaultSeverity: "critical",
		Why: "A pipeline references an exporter that is not defined in the exporters section. The collector will fail to start.",
		BadExample: "service:\n  pipelines:\n    traces:\n      exporters: [missing_exp]",
		GoodExample: "exporters:\n  debug: {}\nservice:\n  pipelines:\n    traces:\n      exporters: [debug]",
		HowToFix: "Define the missing exporter in the exporters section, or remove the reference from the pipeline.",
	},
	"OTEL-STRUCT-004": {
		Title: "Undefined extension reference",
		Category: "structural",
		DefaultSeverity: "high",
		Why: "service.extensions references an extension that is not defined. The collector will log a warning and the extension will not be active.",
		BadExample: "service:\n  extensions: [missing_ext]",
		GoodExample: "extensions:\n  health_check:\n    endpoint: \"0.0.0.0:13133\"\nservice:\n  extensions: [health_check]",
		HowToFix: "Define the extension in the extensions section, or remove the reference from service.extensions.",
	},
	"OTEL-STRUCT-005": {
		Title: "Unused receiver",
		Category: "structural",
		DefaultSeverity: "low",
		Why: "A receiver is defined but never referenced in any pipeline. This is dead configuration that may confuse operators.",
		BadExample: "receivers:\n  otlp: {}\n  jaeger: {}\nservice:\n  pipelines:\n    traces:\n      receivers: [otlp]",
		GoodExample: "receivers:\n  otlp: {}\nservice:\n  pipelines:\n    traces:\n      receivers: [otlp]",
		HowToFix: "Add the unused receiver to a pipeline, or remove the receiver definition.",
	},
	"OTEL-STRUCT-006": {
		Title: "Unused processor",
		Category: "structural",
		DefaultSeverity: "low",
		Why: "A processor is defined but never referenced in any pipeline.",
		BadExample: "processors:\n  batch: {}\n  filter: {}\nservice:\n  pipelines:\n    traces:\n      processors: [batch]",
		GoodExample: "processors:\n  batch: {}\nservice:\n  pipelines:\n    traces:\n      processors: [batch]",
		HowToFix: "Add the unused processor to a pipeline, or remove the processor definition.",
	},
	"OTEL-STRUCT-007": {
		Title: "Unused exporter",
		Category: "structural",
		DefaultSeverity: "low",
		Why: "An exporter is defined but never referenced in any pipeline.",
		BadExample: "exporters:\n  debug: {}\n  otlp: {}\nservice:\n  pipelines:\n    traces:\n      exporters: [debug]",
		GoodExample: "exporters:\n  debug: {}\nservice:\n  pipelines:\n    traces:\n      exporters: [debug]",
		HowToFix: "Add the unused exporter to a pipeline, or remove the exporter definition.",
	},
	"OTEL-STRUCT-008": {
		Title: "Empty pipeline",
		Category: "structural",
		DefaultSeverity: "high",
		Why: "A pipeline has no receivers or no exporters. The pipeline will not process any data.",
		BadExample: "service:\n  pipelines:\n    traces:\n      receivers: []\n      exporters: []",
		GoodExample: "service:\n  pipelines:\n    traces:\n      receivers: [otlp]\n      exporters: [debug]",
		HowToFix: "Add at least one receiver and at least one exporter to the pipeline.",
	},

	"OTEL-REL-101": {
		Title: "memory_limiter processor missing",
		Category: "reliability",
		DefaultSeverity: "high (production), medium (staging)",
		Why: "Without a memory_limiter, a traffic spike may cause the collector to exceed its memory limit and be OOM-killed.",
		BadExample: "processors:\n  batch: {}\nservice:\n  pipelines:\n    traces:\n      processors: [batch]",
		GoodExample: "processors:\n  memory_limiter:\n    limit_mib: 512\n  batch: {}\nservice:\n  pipelines:\n    traces:\n      processors: [memory_limiter, batch]",
		HowToFix: "Add a memory_limiter processor with appropriate limit_mib and spike_limit_mib values.",
	},
	"OTEL-REL-102": {
		Title: "memory_limiter not first processor",
		Category: "reliability",
		DefaultSeverity: "high (production), medium (staging), low (development)",
		Why: "memory_limiter should be the first processor in the chain to catch memory spikes early, before other processors allocate additional memory.",
		BadExample: "processors: [batch, memory_limiter]",
		GoodExample: "processors: [memory_limiter, batch]",
		HowToFix: "Move memory_limiter to the first position in the processor list. Use oteldoctor fix to apply this automatically.",
	},
	"OTEL-REL-103": {
		Title: "Batch processor missing",
		Category: "reliability",
		DefaultSeverity: "medium (production), low (development)",
		Why: "Without batching, the collector may generate excessive network requests under load, increasing backend pressure and cost.",
		BadExample: "processors:\n  memory_limiter: {}\nservice:\n  pipelines:\n    traces:\n      processors: [memory_limiter]",
		GoodExample: "processors:\n  memory_limiter: {}\n  batch:\n    timeout: 200ms\nservice:\n  pipelines:\n    traces:\n      processors: [memory_limiter, batch]",
		HowToFix: "Add a batch processor with appropriate timeout and send_batch_size values.",
	},
	"OTEL-REL-104": {
		Title: "Batch before transform/filter",
		Category: "reliability",
		DefaultSeverity: "medium (production), low (development)",
		Why: "Batching before transformation may result in sending unprocessed data. Transform/filter processors should run before batching.",
		BadExample: "processors: [batch, filter]",
		GoodExample: "processors: [filter, batch]",
		HowToFix: "Move the batch processor to the end of the processor chain, after all transform/filter processors.",
	},
	"OTEL-REL-105": {
		Title: "Exporter retry_on_failure not configured",
		Category: "reliability",
		DefaultSeverity: "medium (production), low (staging/development)",
		Why: "Without retry_on_failure, transient backend errors may cause permanent data loss.",
		BadExample: "exporters:\n  otlphttp:\n    endpoint: \"https://backend:4318\"",
		GoodExample: "exporters:\n  otlphttp:\n    endpoint: \"https://backend:4318\"\n    retry_on_failure:\n      enabled: true",
		HowToFix: "Add a retry_on_failure block to the exporter configuration. Not required for debug exporter.",
	},
	"OTEL-REL-106": {
		Title: "Exporter sending_queue not configured",
		Category: "reliability",
		DefaultSeverity: "medium (production), low (staging/development)",
		Why: "Without a sending_queue, backpressure from the backend may cause pipeline stalls and dropped data.",
		BadExample: "exporters:\n  otlphttp:\n    endpoint: \"https://backend:4318\"",
		GoodExample: "exporters:\n  otlphttp:\n    endpoint: \"https://backend:4318\"\n    sending_queue:\n      num_consumers: 10",
		HowToFix: "Add a sending_queue block to the exporter configuration. Not required for debug exporter.",
	},
	"OTEL-REL-107": {
		Title: "health_check extension missing in production",
		Category: "reliability",
		DefaultSeverity: "medium",
		Why: "In production, the collector should expose a health endpoint for orchestrator health probes.",
		BadExample: "service:\n  pipelines:\n    traces: ...",
		GoodExample: "extensions:\n  health_check:\n    endpoint: \"0.0.0.0:13133\"\nservice:\n  extensions: [health_check]",
		HowToFix: "Add a health_check extension and include it in service.extensions.",
	},
	"OTEL-REL-108": {
		Title: "health_check extension not enabled",
		Category: "reliability",
		DefaultSeverity: "low",
		Why: "The health_check extension is defined but not listed in service.extensions. The health endpoint will not be active.",
		BadExample: "extensions:\n  health_check: {}\nservice:\n  extensions: []",
		GoodExample: "extensions:\n  health_check: {}\nservice:\n  extensions: [health_check]",
		HowToFix: "Add \"health_check\" to the service.extensions list.",
	},

	"OTEL-SEC-201": {
		Title: "Plain HTTP exporter endpoint in production",
		Category: "security",
		DefaultSeverity: "high",
		Why: "Using plain HTTP for exporter endpoints in production may expose telemetry data to interception.",
		BadExample: "exporters:\n  otlphttp:\n    endpoint: \"http://backend:4318\"",
		GoodExample: "exporters:\n  otlphttp:\n    endpoint: \"https://backend:4318\"\n    tls:\n      insecure: false",
		HowToFix: "Use HTTPS for the exporter endpoint, or enable TLS configuration.",
	},
	"OTEL-SEC-202": {
		Title: "Possible hardcoded secret",
		Category: "security",
		DefaultSeverity: "critical",
		Why: "Hardcoded secrets in configuration files are a security risk. They may be exposed in version control or logs.",
		BadExample: "exporters:\n  otlphttp:\n    headers:\n      X-API-KEY: \"abc123\"",
		GoodExample: "exporters:\n  otlphttp:\n    headers:\n      X-API-KEY: \"${env:API_KEY}\"",
		HowToFix: "Use environment variable expansion (e.g. ${env:API_KEY}) or a secret store instead of hardcoded values.",
	},
	"OTEL-SEC-203": {
		Title: "Receiver bound to 0.0.0.0 without auth/TLS",
		Category: "security",
		DefaultSeverity: "high (production only)",
		Why: "Binding to 0.0.0.0 without authentication or TLS may expose the collector to untrusted traffic in production.",
		BadExample: "receivers:\n  otlp:\n    protocols:\n      grpc:\n        endpoint: \"0.0.0.0:4317\"",
		GoodExample: "receivers:\n  otlp:\n    tls:\n      cert_file: /tls/cert.pem\n    protocols:\n      grpc:\n        endpoint: \"0.0.0.0:4317\"",
		HowToFix: "Add TLS configuration, enable authentication, or bind to a specific internal interface.",
	},
	"OTEL-SEC-204": {
		Title: "Debug exporter used in production",
		Category: "security",
		DefaultSeverity: "medium",
		Why: "The debug exporter writes telemetry data to stdout, which may leak sensitive information in production logs.",
		BadExample: "service:\n  pipelines:\n    traces:\n      exporters: [debug]",
		GoodExample: "service:\n  pipelines:\n    traces:\n      exporters: [otlphttp]",
		HowToFix: "Remove the debug exporter from production pipelines.",
	},
	"OTEL-SEC-205": {
		Title: "Pprof or zpages on public interface",
		Category: "security",
		DefaultSeverity: "high (production), medium (staging), low (development)",
		Why: "Debug extensions exposed on non-localhost interfaces may be reachable from untrusted networks.",
		BadExample: "extensions:\n  pprof:\n    endpoint: \"0.0.0.0:1777\"",
		GoodExample: "extensions:\n  pprof:\n    endpoint: \"localhost:1777\"",
		HowToFix: "Bind debug extensions to localhost or an internal network interface only.",
	},
	"OTEL-SEC-206": {
		Title: "TLS configuration missing for remote exporter",
		Category: "security",
		DefaultSeverity: "high (production), medium (staging/development)",
		Why: "Exporters targeting remote endpoints without TLS configuration may send data in plaintext.",
		BadExample: "exporters:\n  otlphttp:\n    endpoint: \"https://backend:4318\"",
		GoodExample: "exporters:\n  otlphttp:\n    endpoint: \"https://backend:4318\"\n    tls:\n      insecure: false",
		HowToFix: "Add TLS configuration (insecure: false, or custom CA/cert settings) to the exporter.",
	},
	"OTEL-SEC-207": {
		Title: "Auth extension not enabled",
		Category: "security",
		DefaultSeverity: "medium",
		Why: "An authentication extension is defined but not listed in service.extensions. It will not be active.",
		BadExample: "extensions:\n  oauth2client:\n    client_id: abc\nservice:\n  extensions: []",
		GoodExample: "extensions:\n  oauth2client:\n    client_id: abc\nservice:\n  extensions: [oauth2client]",
		HowToFix: "Add the auth extension to the service.extensions list.",
	},

	"OTEL-COST-301": {
		Title: "High-cardinality attribute in metric dimensions",
		Category: "cost",
		DefaultSeverity: "medium",
		Why: "Using high-cardinality attributes (e.g. user.id, trace_id, http.url) as metric dimensions causes unbounded metric series growth, increasing storage and query costs.",
		BadExample: "processors:\n  attributes:\n    actions:\n      - key: user.id\n        action: upsert",
		GoodExample: "processors:\n  attributes:\n    actions:\n      - key: service.name\n        action: upsert",
		HowToFix: "Remove high-cardinality dimensions, use pre-aggregation, or limit to a fixed set of values.",
	},
	"OTEL-COST-302": {
		Title: "Transform processor creates dynamic attributes",
		Category: "cost",
		DefaultSeverity: "medium",
		Why: "Dynamic attributes created by transform processors at runtime can increase per-metric cardinality and storage cost.",
		BadExample: "processors:\n  transform:\n    metric_statements:\n      - set(description, \"custom\")",
		GoodExample: "Use pre-defined attribute sets instead of dynamic set() calls.",
		HowToFix: "Limit dynamic attributes to known values or use pre-defined attribute sets.",
	},
	"OTEL-COST-303": {
		Title: "Spanmetrics connector uses risky dimensions",
		Category: "cost",
		DefaultSeverity: "medium",
		Why: "The spanmetrics connector without explicit dimensions may turn all span attributes into metric dimensions, causing unbounded cardinality.",
		BadExample: "connectors:\n  spanmetrics:\n    histogram: {}",
		GoodExample: "connectors:\n  spanmetrics:\n    dimensions:\n      - name: service.name\n    histogram: {}",
		HowToFix: "Define an explicit dimensions list to limit which attributes become metric dimensions.",
	},
	"OTEL-COST-304": {
		Title: "Debug exporter may emit high volume",
		Category: "cost",
		DefaultSeverity: "medium",
		Why: "The debug exporter writes every span to stdout, generating excessive I/O volume in production.",
		BadExample: "service:\n  pipelines:\n    traces:\n      exporters: [debug]",
		GoodExample: "service:\n  pipelines:\n    traces:\n      exporters: [otlphttp]",
		HowToFix: "Remove the debug exporter from production pipelines to reduce log volume and infrastructure cost.",
	},
	"OTEL-COST-305": {
		Title: "Traces pipeline has no sampling",
		Category: "cost",
		DefaultSeverity: "high",
		Why: "Without sampling, all traces are exported. In production, this may cause high backend costs and network egress charges.",
		BadExample: "processors: [batch]\nservice:\n  pipelines:\n    traces:\n      processors: [batch]",
		GoodExample: "processors:\n  tailsampling:\n    policies:\n      - name: keep-all\n        type: always_sample\n  batch: {}\nservice:\n  pipelines:\n    traces:\n      processors: [tailsampling, batch]",
		HowToFix: "Add a tailsampling, probabilisticsampler, or filter processor to control trace volume.",
	},

	"OTEL-SEM-401": {
		Title: "service.name not configured",
		Category: "semantic",
		DefaultSeverity: "low",
		Why: "Without an explicit service.name, the service identity may be inconsistent across deployments, making it harder to correlate telemetry.",
		BadExample: "processors:\n  batch: {}",
		GoodExample: "processors:\n  resource:\n    attributes:\n      - key: service.name\n        value: \"my-service\"\n        action: upsert",
		HowToFix: "Set service.name using a resource processor or via the OTEL_SERVICE_NAME environment variable.",
	},
	"OTEL-SEM-402": {
		Title: "Legacy service name attribute used",
		Category: "semantic",
		DefaultSeverity: "medium",
		Why: "app_name or application_name are non-standard. The standard semantic convention is service.name.",
		BadExample: "processors:\n  resource:\n    attributes:\n      - key: app_name\n        value: \"legacy\"\n        action: upsert",
		GoodExample: "processors:\n  resource:\n    attributes:\n      - key: service.name\n        value: \"my-service\"\n        action: upsert",
		HowToFix: "Replace app_name or application_name with the standard service.name attribute.",
	},
	"OTEL-SEM-403": {
		Title: "deployment.environment missing in production",
		Category: "semantic",
		DefaultSeverity: "medium",
		Why: "Without deployment.environment, telemetry data may be missing the environment dimension, making it harder to distinguish production from non-production data.",
		BadExample: "processors:\n  resource:\n    attributes:\n      - key: service.name\n        value: my-service\n        action: upsert",
		GoodExample: "processors:\n  resource:\n    attributes:\n      - key: deployment.environment\n        value: production\n        action: upsert",
		HowToFix: "Set deployment.environment to \"production\" using a resource processor.",
	},
	"OTEL-SEM-404": {
		Title: "service.version missing in production",
		Category: "semantic",
		DefaultSeverity: "low",
		Why: "Including the service version helps correlate telemetry with deployments and simplifies debugging.",
		BadExample: "processors:\n  resource:\n    attributes:\n      - key: service.name\n        value: my-service\n        action: upsert",
		GoodExample: "processors:\n  resource:\n    attributes:\n      - key: service.version\n        value: \"1.2.3\"\n        action: upsert",
		HowToFix: "Set service.version using a resource processor or via the OTEL_RESOURCE_ATTRIBUTES environment variable.",
	},
	"OTEL-SEM-405": {
		Title: "Deprecated semantic attribute detected",
		Category: "semantic",
		DefaultSeverity: "low",
		Why: "Deprecated attribute names may cause inconsistent behavior across OpenTelemetry SDK versions and backends.",
		BadExample: "processors:\n  resource:\n    attributes:\n      - key: http.method\n        action: upsert",
		GoodExample: "processors:\n  resource:\n    attributes:\n      - key: http.request.method\n        action: upsert",
		HowToFix: "Rename deprecated attributes to their current semantic convention equivalents (e.g. http.method -> http.request.method).",
	},

	"OTEL-K8S-501": {
		Title: "memory_limiter too close to container limit",
		Category: "kubernetes",
		DefaultSeverity: "medium",
		Why: "If memory_limiter.limit_mib is at or near the container memory limit, the collector may be OOM-killed before memory_limiter activates.",
		BadExample: "Container memory limit: 512Mi\nmemory_limiter.limit_mib: 512",
		GoodExample: "Container memory limit: 512Mi\nmemory_limiter.limit_mib: 400\nGOMEMLIMIT: 400MiB",
		HowToFix: "Set memory_limiter.limit_mib to at most 80% of the container memory limit and set GOMEMLIMIT.",
	},
	"OTEL-K8S-502": {
		Title: "GOMEMLIMIT missing",
		Category: "kubernetes",
		DefaultSeverity: "medium",
		Why: "Without GOMEMLIMIT, the Go runtime may not release memory back to the OS, leading to OOM kills under sustained load.",
		BadExample: "env:\n  - name: OTEL_SERVICE_NAME\n    value: otel-collector",
		GoodExample: "env:\n  - name: GOMEMLIMIT\n    value: \"400MiB\"",
		HowToFix: "Set GOMEMLIMIT to 80% of the container memory limit (e.g. GOMEMLIMIT=400MiB for a 512Mi container).",
	},
	"OTEL-K8S-503": {
		Title: "Container resources not defined",
		Category: "kubernetes",
		DefaultSeverity: "medium",
		Why: "Without resource limits, the collector may consume unbounded resources on the node, affecting other workloads.",
		BadExample: "containers:\n  - name: otel-collector\n    image: otel/opentelemetry-collector:latest",
		GoodExample: "containers:\n  - name: otel-collector\n    resources:\n      limits:\n        memory: \"512Mi\"\n        cpu: \"500m\"",
		HowToFix: "Set resources.limits.memory and resources.limits.cpu for the collector container.",
	},
	"OTEL-K8S-504": {
		Title: "Kubernetes probe missing for health_check",
		Category: "kubernetes",
		DefaultSeverity: "medium",
		Why: "The health_check extension is enabled but the Kubernetes workload is missing readiness/liveness probes. The orchestrator cannot detect collector health.",
		BadExample: "extensions:\n  health_check: {}\n# Deployment has no probes",
		GoodExample: "extensions:\n  health_check: {}\n# Deployment includes readinessProbe and livenessProbe",
		HowToFix: "Add a readinessProbe and livenessProbe to the collector container, targeting the health_check endpoint.",
	},
	"OTEL-K8S-505": {
		Title: "Receiver exposed as LoadBalancer",
		Category: "kubernetes",
		DefaultSeverity: "medium (production only)",
		Why: "A LoadBalancer service in production may expose the collector's receiver to the public internet.",
		BadExample: "apiVersion: v1\nkind: Service\nspec:\n  type: LoadBalancer",
		GoodExample: "apiVersion: v1\nkind: Service\nspec:\n  type: ClusterIP",
		HowToFix: "Use an internal load balancer or ClusterIP with an ingress controller that provides authentication.",
	},
}

func GetRuleDoc(ruleID string) (RuleDoc, bool) {
	doc, ok := ruleDocs[ruleID]
	return doc, ok
}
